import type { Metadata } from 'next';
import { ReactNode } from 'react';
import Link from 'next/link';
import Head from './head';
import '../styles/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface Props {
  children: ReactNode;
}

export default function RootLayout({ children }: Props) {
  const header = (
    <header>
      <div className="text-center bg-slate-800 p-8 my-6 rounded-md">
        <Link href="/">
          <h1 className="text-3xl text-white font-bold">Xtring's Blog</h1>
        </Link>
        <p className="text-slate-300">🤘🏻 Welcome to my Tech Blog</p>
      </div>
    </header>
  );

  const footer = (
    <footer>
      <div className="border-t border-slate-400 mt-12 py-12 text-center">
        <h3 className="text-slate-400">Designed by Xtring</h3>
      </div>
    </footer>
  );

  return (
    <html lang="ko">
      <Head />
      <body>
        <div className="mx-auto max-w-2xl px-6">
          {header}
          {children}
          {footer}
        </div>
      </body>
    </html>
  );
}
